### PR TITLE
Instruction changes

### PR DESCRIPTION
**Pull request by ultraJeff**
Hey all,

Thanks for reviewing this! I've been looking closely at the instructions since I plan on workshopping this on the 28th. Based on my experiences going through it, I think the changes I'm proposing will help to add clarity in places where learners might struggle and, overall, improve the flow of the workshop.

I also fixed up various small things and design inconsistencies.

Thanks for putting the workshop together in the first place, and thank you again for reviewing these changes!

### CODE REVIEW

**Comment by ultraJeff** [comment]
@gnunn1 @thoraxe - I probably should have tagged you all initially! Thanks in advance for reviewing this PR. Please let me know if there are any comments, or whether these changes look good to y'all!

**Comment by gnunn1** [comment]
@ultraJeff Thanks for the PR Jeff, it looks good but a couple of comments:

1. Instead of adding the comment about Argo Rollouts how about we just qualify the rollout line further:

`Wait for the rollout of the new pods to happen in the deployment:`

Including a mention of Argo Rollouts is potentially confusing to users who are not familiar with the Argo ecosystem.

2. There is a typo of `and` as `amd` in your changes:

`Kustomize can also be used to write a new YAML file amd pipe into`

**Comment by ultraJeff** [comment]
Hey @gnunn1 - thanks for the rollouts suggestion and good catch on the typo! I've corrected both now and am ready for a re-review.

**Comment by gnunn1** [comment]
Merged, thanks for the PR Jeff, much appreciated!

**Pull request merged**
